### ISSUE TITLE
naiveproxy 插件

### ISSUE THREAD

**Issue by shawnisbeing** [MatsuriDayo/plugins#11]
大佬能否开发个naiveproxy 插件,最近其他几个协议封端口和封IP很严重,目前看来就是naiveproxy最稳定,但是nekoray还没有naiveproxy的插件啊,,谢谢!

**Comment by arm64v8a** [comment]
Matsuri 暂时使用 SagerNet naive-plugin

Nekoray naiveproxy 不需要插件，但是要下载内核 https://github.com/klzgrad/naiveproxy/releases

**Comment by shawnisbeing** [comment]
感谢大佬回复,谢谢,我按照提示下载了MAC的naiveproxy内核,在基本设置-核心里面也添加了naiveproxy内核路劲,但是还是提示错误:
[2022-11-21 21:50:21] [Warning] V2Ray 5.1.0 started
[Naive] [Error] Program exited accidentally: 未知错误
启动的时候从还是从默认的V2Ray启动了?
我这里是不是少了什么?
感谢!
