### ISSUE TITLE
Please update hysteria and xray

### ISSUE THREAD

**Issue by showgood163** [MatsuriDayo/plugins#14]
See

https://github.com/apernet/hysteria/releases/tag/v1.3.3

https://github.com/XTLS/Xray-core/releases/tag/v1.7.5

**Comment by t-e-s-tweb** [comment]
> See
> 
> https://github.com/apernet/hysteria/releases/tag/v1.3.2
> 
> https://github.com/XTLS/Xray-core/releases/tag/v1.6.6

Fork the repo and make new releases yourself when a new update for x-ray or another plugin comes. It's super easy and then just self sign.

**Comment by showgood163** [comment]
> epo and make new releases yourself when a new update for x-ray or another plugin comes. It's super easy and then just self sign.

OK, thanks.
