### ISSUE TITLE
Please update xray plugin to 1.7

### ISSUE THREAD

**Issue by Graveyard9988** [MatsuriDayo/plugins#15]
Regards

**Comment by Jimmisama** [comment]
1.7.2 now. IIRC The plugin author and matsuri author isn't the same person.

**Comment by Graveyard9988** [comment]
So who should I ask for?

**Comment by Jimmisama** [comment]
> So who should I ask for?

I don't actually know...

**Comment by Jimmisama** [comment]
Updated.
