### ISSUE TITLE
Can you build a 32bits plugin for me?

### ISSUE THREAD

**Issue by ironmantonystark** [MatsuriDayo/plugins#25]
one of my phones is a phone with a 32bits CPU, can you build the TUIC plugin 32bits as well, if possible, please push them to Google play too, thank you so much
I tried to build them on the Android Studio, it was successfully built the 32bits unsigned release apk files, but unfortunately Android didn't allow me to install it due to security reasons

**Comment by hibobmaster** [comment]
可以参考：
https://developer.android.com/studio/publish/app-signing
https://developer.android.com/studio/build/building-cmdline
