### ISSUE TITLE
Please upgrade xray plugin to latest release

### ISSUE THREAD

**Issue by Graveyard9988** [MatsuriDayo/plugins#30]
I'm not a programmer

Please consider new update for xray plugin

Regards

**Comment by ODtian** [comment]
you mean 1.8.0 pre-release? need it too

**Comment by KevinMX** [comment]
You may want to try: https://github.com/MatsuriDayo/NekoBoxForAndroid

**Comment by Graveyard9988** [comment]
None of my less configs can't be connected in this new client. It needs
header!

**Comment by maskedeken** [comment]
You can try [my build](https://github.com/maskedeken/plugins/releases/tag/Xray-v1.8.0-3) which supports VLESS over reality protocol

**Comment by Graveyard9988** [comment]
> You can try [my build](https://github.com/maskedeken/plugins/releases/tag/Xray-v1.8.0-3) which supports VLESS over reality protocol

Thanks a million sir. Please keep these plugins updated.
