### ISSUE TITLE
[Request] add naiveproxy plugin because sagernet/plugins is gone

### ISSUE THREAD

**Issue by showgood163** [MatsuriDayo/plugins#36]
Now https://github.com/sagernet/plugins/ is gone

**Comment by egg1234** [comment]
你可以在下面的连接下载111版的插件
https://github.com/SagerNet/SagerNet/releases/tag/naive-plugin-111.0.5563.64-1

至于113版的插件，由于发布的Co-authored-by: _haku_ <136535642@qq.com>公开了真实的联系方式，这个是比较奇怪的，你自己衡量是否合适使用
https://github.com/SagerNet/SagerNet/releases/tag/naive-plugin-113.0.5672.62-2

**Comment by showgood163** [comment]
额。好久没在sagernet那边下载插件，忘了这茬了。
