### ISSUE TITLE
Plugin system doesnt allow to bypass plugin

### ISSUE THREAD

**Issue by uoosef** [MatsuriDayo/plugins#42]
Hello,
I wrote a nekobox plugin thats doing **tls fragmentation**, and this process requires that nekobox allows the plugin to connect to internet freely

this is the config that i wrote in my main.js and as you see i added **needBypassRootUid: true,** but it doesnt work and traffic getting back to executable file socks port

```js
let plgConfig = {
    ok: true,
    reason: "",
    minVersion: 1,
    protocols: [
      {
        protocolId: "bepass",
        links: ["bepass://"],
        haveStandardLink: false,
        canShare: true,
        canMux: false,
        canMapping: false,
        canTCPing: false,
        canICMPing: false,
        needBypassRootUid: true,
      }
    ],
  };
```

My app id ismoe.matsuri.plugin.bepass  and this is my build.gradle.kts file

```kotlin
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

setupAll()

android {
    defaultConfig {
        applicationId = "moe.matsuri.plugin.bepass"
        versionCode = 1
        versionName = "1.1.10"
    }
}
```

if you add somthing that i can remove nekobox itself from the vpn service i can publish my work and many people in iran can bypass dpi and watch youtube without needing a vpn server

Thanx

**Comment by uoosef** [comment]
Also if it helps 

this is the nekobox plugin repository

https://github.com/uoosef/nekobepass

and this is the bepass project repository

https://github.com/uoosef/bepass

**Comment by arm64v8a** [comment]
`needBypassRootUid` This option has not been maintained for a long time, maybe it no longer works.

If you need a rootless bypass, use `protect_path` like [here](https://github.com/juicity/juicity/commit/cd9f6e5d220613e188c053062375ecec09ab8a65#diff-d444dbf96dccfd38aea53c42b446ba67d8261aed84b4867e313e63e0039091fdR40)

If you require root privileges, you can use this method, or directly use `setsockopt`.

**Comment by uoosef** [comment]
thank you very much it worked !
