### ISSUE TITLE
 juicity v7a

### ISSUE THREAD

**Issue by Mo-hdb44** [MatsuriDayo/plugins#44]
Please add plugin for 32-bit phones

**Comment by BBC-FOX** [comment]
顶一个，恳请大神出juicity v7a的版本，用以支持低端手机和电视的安卓系统啊！

**Comment by Misaka-blog** [comment]
有计划考虑

**Comment by Misaka-blog** [comment]
抱歉，官方不支持 arm32-v7a

![image](https://github.com/MatsuriDayo/plugins/assets/122191366/78384858-de68-4833-9378-2e13e3c1e8bc)
